name: editorial_pulse
description: تطبيق تسوق مع تصميم Editorial Pulse
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1           # للخطوط العربية والأجنبية
  flutter_svg: ^2.0.9            # للـ SVGs إذا وجدت
  cupertino_icons: ^1.0.6
  provider: ^6.1.1               # لإدارة الحالة
  intl: ^0.18.1                  # للتنسيقات الرقمية والعملات

  flutter_launcher_icons: "^0.13.1" 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


# 👇 قسم أيقونة التطبيق
flutter_launcher_icons:
  android: true
  ios: false  # لأنك تريد للأندرويد فقط
  image_path: "assets/logo.png"  # ضع مسار اللوجو هنا
  adaptive_icon_background: "#ffffff"  # لون خلفية الأيقونة التكيفية (اختياري)
  adaptive_icon_foreground: "assets/logo.png"  # الأيقونة الأمامية للأندرويد 8+
  